language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
script:
  - python -m doctest ./retry.py
  - ./retry.py -n 5 -c ./tests/random.sh || true
  - ./retry.py -n 3 -m 1,2-3 -c ./tests/parameter.sh @
